import '../workbenchActions'
import '../hostCommands'
import '../folderCommands'
import '../connectionClipboardCommands'
import '../nodeCommands'
import '../tabCommands'
import '../terminalCommands'
import '../sftp/file-commands'

export { MenuId, HOST_MENU_ID, NODE_MENU_ID, TAB_MENU_ID, TERMINAL_MENU_ID } from './menuIds'
